server:
  port: 8006
  netty:
    idle-timeout: 60s                     # Закрытие неактивных соединений через 60 секунд
    connection-timeout: 30s               # Тайм-аут установки соединения
    max-connections: 10000                # Максимальное количество одновременных соединений
    validate-headers: true                # Проверка HTTP-заголовков
spring:
  application:
    name: flex-internet-shop
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    pool:
      enabled: true
      initial-size: 5
      max-size: 15
      max-idle-time: 30s
      max-life-time: 10m
      validation-query: SELECT 1
  sql:
    init:
      mode: always
