server:
  port: 8006
spring:
  application:
    name: mvc-internet-shop
  jpa:
    show_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    host: localhost
    port: 5432
    database: postgres
    username: postgres
    password: postgres
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}?autoReconnect=true
    hikari:
      maximumPoolSize: 6
      minimumIdle: 4
      driverClassName: org.postgresql.Driver
      jdbcUrl: ${spring.datasource.url}
  liquibase:
    change-log: classpath:changelog/db.changelog-master.xml
    enabled: true
    default-schema: public
